[env:esp32-c6-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

; Force PlatformIO to generate the compilation database for CLion
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include

; Tell PlatformIO which tools to use for "Static Code Analysis"
check_tool = cppcheck, clangtidy
check_skip_packages = yes